### ISSUE TITLE
FIX THE CONTRACT WEB ADDRESS IN FOOTER

### ISSUE THREAD

**Issue by KimTudor** [jaredtmartin/dannyronsrescue#39]
Still has incorrect web address in footer

<img width="435" alt="screen shot 2016-12-06 at 2 58 04 pm" src="https://cloud.githubusercontent.com/assets/24417428/21126261/2b3b42cc-c0b9-11e6-98dd-61f2ebba602e.png">

**Comment by jaredtmartin** [comment]
This has already been changed. The system saves a copy of the contract when it's generated.  It will automatically generate a new one when the dogs info changes or it can't find an existing contract.  This screenshot is probably a contract that was already generated before I made the change.  If you want I can delete all the stored contracts so the system will automatically regenerate them upon request.
